datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/signupprac?useUnicode=true&characterEncoding=UTF-8
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true

jwtpassword:
  source: ${JWT_SECRET_KEY}

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.SQL: debug
